// Autogenerated file, do not edit!
// Generated from battleships contract
import { loadContractArtifact } from '@aztec/aztec.js/abi';
import { AztecAddress } from '@aztec/aztec.js/addresses';
import { Contract, ContractBase, DeployMethod } from '@aztec/aztec.js/contracts';
import { PublicKeys } from '@aztec/aztec.js/keys';
import type { ContractArtifact, ContractInstanceWithAddress } from '@aztec/aztec.js/abi';
import type { ContractFunctionInteraction, ContractMethod } from '@aztec/aztec.js/contracts';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BattleshipsContractArtifactJson from '../target/battleships-Battleships.json' assert { type: 'json' };

export const BattleshipsContractArtifact = loadContractArtifact(BattleshipsContractArtifactJson as ContractArtifact);

/**
 * Type-safe interface for Battleships contract
 */
export class BattleshipsContract extends ContractBase {

  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet
  ) {
    super(instance, BattleshipsContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet
  ): Promise<BattleshipsContract> {
    return Contract.at(address, BattleshipsContract.artifact, wallet) as Promise<BattleshipsContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod(PublicKeys.default(), wallet, BattleshipsContractArtifact, BattleshipsContract.at);
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BattleshipsContractArtifact;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {

    /** create_game(game_id: struct, board: struct, initial_shot: struct) */
    create_game: ((game_id: any, board: any, initial_shot: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** join_game(game_id: struct, board: struct, initial_shot: struct) */
    join_game: ((game_id: any, board: any, initial_shot: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** shoot(game_id: struct, turn: u32, shot: struct) */
    shoot: ((game_id: any, turn: any, shot: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** claim_abandonment(game_id: struct, turn: u32) */
    claim_abandonment: ((game_id: any, turn: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** get_game_status(game_id: struct) */
    get_game_status: ((game_id: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
